# from fduthesis: https://github.com/stone-zeng/fduthesis/blob/master/.github/workflows/test.yml

name: Build

on: [push]

env:
  CTAN_URL: https://mirrors.rit.edu/CTAN

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    if: "!endsWith(github.event.head_commit.message, '[ci skip]')"
    steps:
    - uses: actions/checkout@v2
    - name: Install TeX Live
      run: |
        export PATH=/tmp/texlive/bin/x86_64-linux:$PATH
        wget ${{ env.CTAN_URL }}/systems/texlive/tlnet/install-tl-unx.tar.gz
        tar -xzf install-tl-unx.tar.gz
        cd install-tl-20* && ./install-tl --profile ../.github/workflows/texlive.profile
    - name: Build user document
      run: |
        export PATH=/tmp/texlive/bin/x86_64-linux:$PATH
        latexmk -pdflua
  build-macos:
    runs-on: macos-latest
    if: "!endsWith(github.event.head_commit.message, '[ci skip]')"
    steps:
    - uses: actions/checkout@v2
    - name: Install TeX Live
      run: |
        export PATH=/tmp/texlive/bin/x86_64-darwin:$PATH
        curl -O ${{ env.CTAN_URL }}/systems/texlive/tlnet/install-tl-unx.tar.gz
        tar -xzf install-tl-unx.tar.gz
        cd install-tl-20* && ./install-tl --profile ../.github/workflows/texlive.profile
        tlmgr conf texmf OSFONTDIR /System/Library/AssetsV2/com_apple_MobileAsset_Font6
    - name: Build user document
      run: |
        export PATH=/tmp/texlive/bin/x86_64-darwin:$PATH
        latexmk -pdflua
  # Line wrap problem is difficult to resolve on windows.
  build-windows:
    runs-on: windows-latest
    if: "!endsWith(github.event.head_commit.message, '[ci skip]')"
    steps:
    - uses: actions/checkout@v2
    - name: Install TeX Live
      run: |
        ${env:PATH} = "${{ github.workspace }}\tmp\texlive\bin\win32;" + ${env:PATH}
        Invoke-WebRequest -Uri ${{ env.CTAN_URL }}/systems/texlive/tlnet/install-tl.zip -OutFile install-tl.zip
        Expand-Archive install-tl.zip -DestinationPath .
        Set-Location install-tl-*
        .\install-tl-windows --no-gui --profile ..\.github\workflows\texlive-win.profile
    - name: Build user document
      run: |
        ${env:PATH} = "${{ github.workspace }}\tmp\texlive\bin\win32;" + ${env:PATH}
        latexmk -pdflua