name: Build

on:
  push:
  schedule:
  - cron: "0 0 * * *"

jobs:
  build_on_macos:
    name: Build thesis on macOS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install macTeX
      run: |
        brew cask install mactex-no-gui
    - name: Build thesis
      run: |
        eval "$(/usr/libexec/path_helper)"
        tlmgr conf texmf OSFONTDIR /System/Library/AssetsV2/com_apple_MobileAsset_Font6
        latexmk -lualatex
  build_on_linux:
    name: Build thesis on Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install TeX Live
      run: |
        sudo apt update
        sudo apt install texlive-full
    - name: Build thesis
      run: |
        latexmk -lualatex
  build_on_windows:
    name: Build thesis on Windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install MiKTeX
      run: |
        choco install miktex
    - name: Build thesis
      run: |
        latexmk -lualatex
